name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up venv
        shell: bash
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m venv .venv

      - name: Install project
        shell: bash
        run: |
          source .venv/bin/activate
          python3 -m pip install ".[dev]"

      - name: Test
        run: .venv/bin/python3 -m pytest --cov=texthero --cov-report=term-missing --cov-report xml --cov-branch

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
